[package]
name = "pgndb"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
clap = { version = "=4.6.6", features = ["cargo"] }
log = "=0.4.33"
env_logger = "=0.11.11"
codespan-reporting = "=0.13.1"
chess_parsers = { path = "../parsers" }
rusqlite = { version = "=0.40.2", features = ["bundled"] }
chess_core = { workspace = true }
chess_common = { workspace = true }
iso_8859_1_encoder = { workspace = true }
